In [1]:
import os
import pandas as pd
from collections import Counter
from Radiomics import Radiomics

In [2]:
# Path for original dataset for segmentation
DATASET_PATH = "../Datasets/OrigDataset"
### DATASET_PATH = "C:\\Users\\krybr\\iCloudDrive\\Documents\\JupyterNotebook\\Datasets\\OrigDataset\\"



# Path for folder with augmented dataset for segmentation 
#### SEG_PATH = "C:\\Users\krybr\\iCloudDrive\\Documents\\JupyterNotebook\Datasets\\new_data\\"

SEG_PATH = "../Datasets/new_data"

# Path for csv file with information about pictures in dataset
CSV_FILE_PATH = os.path.join(DATASET_PATH, "GroundTruth.csv")

# Path for images and masks used for segmentation
#ORIGINAL_DATASET_PATH = os.path.join(SEG_PATH, "images/")
#MASK_DATASET_PATH = os.path.join(SEG_PATH, "masks/")

ORIGINAL_DATASET_PATH = os.path.join(SEG_PATH, "originals")
MASK_DATASET_PATH = os.path.join(SEG_PATH, "masks")

# Path for file with segmentation parameters
PARAMS = 'Params.yaml'

In [3]:
#radiomics_dataset = DatasetForRadiomics(ORIGINAL_DATASET_PATH, MASK_DATASET_PATH, CSV_FILE_PATH)

In [4]:
radiomics_class = Radiomics(ORIGINAL_DATASET_PATH, MASK_DATASET_PATH, CSV_FILE_PATH, PARAMS)

In [5]:
df = radiomics_class.get_radiomics_df()

In [7]:
df

,names,mean_b,mean_g,mean_r,std_b,std_g,std_r
0,[ISIC_0024306_0],23.103522,59.621667,59.933526,37.586955,84.764515,84.960329
1,[ISIC_0024306_1],23.103522,59.621667,59.933526,37.586955,84.764515,84.960329
2,[ISIC_0024306_2],23.745426,59.998211,60.284915,38.731133,84.986426,85.163043
3,[ISIC_0024306_3],21.357804,54.947567,55.218533,36.686619,83.188058,83.369748
4,[ISIC_0024306_4],23.100996,59.624681,59.928856,37.580082,84.769565,84.952349
...,...,...,...,...,...,...,...
60073,[ISIC_0034320_1],56.575659,88.204033,86.874393,65.449479,97.856684,96.564499
60074,[ISIC_0034320_2],57.260493,88.701985,87.346922,65.876448,97.939975,96.605673
60075,[ISIC_0034320_3],48.395074,75.367437,74.202715,63.795640,95.627046,94.295616
60076,[ISIC_0034320_4],56.576219,88.204585,86.868037,65.450015,97.858056,96.558275
60077,[ISIC_0034320_5],56.579004,88.199741,86.872444,65.454027,97.852772,96.562794

In [8]:
df.to_csv("../Datasets/AllForColors.csv")